import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useSWR from 'swr';

import Reading from '../components/Reading/Reading';
import WindComp from '../components/Wind/Wind';
import { APIRoute, Observations, Response } from '../models/api';

const fetcher = (key: string) => fetch(key).then(res => res.json());

const useObservations = (): { observations?: Response<Observations>; isLoading: boolean; isError: boolean } => {
  const { data, error } = useSWR<Response<Observations>>(APIRoute.CURRENT, fetcher);

  return {
    observations: data,
    isLoading: !error && !data,
    isError: error
  };
};

export default function Home() {
  const { observations, isLoading, isError } = useObservations();

  return (
    <div className={styles.container}>
      <Head>
        <title>#aq Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Current Conditions in #aq</h1>

      {observations ? (
        !isError ? (
          <>
            <h1>{observations.data.nws?.textDescription}</h1>
            <div className={styles.main}>
              <Reading title="Temp" value={`${observations.data.wl?.temperature}°`} />
              <Reading title="Feels Like" value={`${observations.data.wl?.feelsLike ?? '–'}°`} />
              <Reading title="Humidity" value={`${observations.data.wl?.humidity}%`} />
              <Reading title="Wind">
                <WindComp wind={observations.data.wl?.wind} />
              </Reading>
            </div>
          </>
        ) : (
          <>
            <h1>Something went wrong :(</h1>
            <br />
            {observations?.errors.map(error => (
              <h3 key={error}>{error}</h3>
            ))}
          </>
        )
      ) : (
        <h1>Hang Tight</h1>
      )}
    </div>
  );
}
