import Head from 'next/head';
import TimeAgo, { Formatter, Suffix, Unit as TimeAgoUnit } from 'react-timeago';
import useSWR from 'swr';

import CardDetail from '../components/CardDetail/CardDetail';
import { APIRoute, BaseObservations, getPath, Observations, Response } from '../models/api';
import styles from '../styles/Home.module.css';

const fetcher = (key: string) => fetch(key).then(res => res.json());

const timeAgoFormatter = ((
  value: number,
  unit: TimeAgoUnit,
  suffix: Suffix,
  epochMiliseconds: number,
  nextFormatter: Formatter
) => {
  if (suffix === 'from now' || (unit === 'second' && value < 30)) {
    return <>just now</>;
  } else if ((unit === 'second' && value >= 30) || (unit === 'minute' && value < 2)) {
    return <>a moment {suffix}</>;
  }
  return nextFormatter(value, unit, suffix, epochMiliseconds);
}) as Formatter;

const useObservations = (): { observations?: Response<Observations>; isLoading: boolean; isError: boolean } => {
  const { data, error } = useSWR<Response<Observations>>(getPath(APIRoute.CURRENT), fetcher);

  return {
    observations: data,
    isLoading: !error && !data,
    isError: error
  };
};

export default function Home() {
  const { observations, isLoading, isError } = useObservations();

  const getWindDirection = (deg: Number) => {
    if (deg > 337.5 || deg <= 22.5) return 'N';
    else if (deg <= 67.5) return 'NE';
    else if (deg <= 112.5) return 'E';
    else if (deg <= 157.5) return 'SE';
    else if (deg <= 202.5) return 'S';
    else if (deg <= 247.5) return 'SW';
    else if (deg <= 292.5) return 'W';
    else if (deg <= 337.5) return 'NW';

    return '';
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>#aq Weather</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex', justifyContent: 'center', margin: '2rem 0rem 3rem' }}>
        <img src="skylines/boston.svg" style={{ height: '8rem', objectFit: 'scale-down' }}></img>
      </div>
      {observations ? (
        !isError ? (
          <>
            <div
              style={{
                background: '#ffffff',
                margin: '1rem 0rem',
                borderRadius: '2px',
                boxShadow: '0px 0.25rem 0.5rem rgba(0, 0, 0, .15)'
              }}
            >
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  flexWrap: 'wrap',
                  minHeight: '3.5rem',
                  backgroundColor: '#5115F7',
                  color: '#FFFFFF'
                }}
              >
                <p
                  style={{
                    margin: '1rem 1rem 0.75rem',
                    fontSize: '1.5rem',
                    fontWeight: '700'
                  }}
                >
                  NOW
                </p>
                <p
                  style={{
                    margin: '1rem',
                    fontSize: '1rem',
                    fontWeight: '300',
                    whiteSpace: 'nowrap'
                  }}
                >
                  Updated{' '}
                  {
                    <TimeAgo
                      date={
                        Math.max(...Object.values(observations.data).map((data: BaseObservations) => data.readTime)) *
                        1_000
                      }
                      formatter={timeAgoFormatter}
                    />
                  }
                </p>
              </div>
              <div
                style={{
                  display: 'flex',
                  flexWrap: 'wrap',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  padding: '0.5rem 1rem'
                }}
              >
                <div style={{ flex: '0 1 auto', marginRight: '1rem' }}>
                  <h1 style={{ margin: '1rem 0rem 0rem', fontSize: '7rem', fontWeight: '400' }}>
                    <span>
                      {observations.data.wl?.temperature != null ? Math.floor(observations.data.wl.temperature) : '–'}
                    </span>
                    <span style={{ fontSize: '2rem' }}>
                      {observations.data.wl?.temperature != null
                        ? `.${(observations.data.wl.temperature * 10) % 10}`
                        : ''}
                    </span>
                    <span style={{ marginLeft: '-0.5rem' }}>°</span>
                  </h1>
                  {observations.data.wl?.feelsLike ? (
                    <p style={{ margin: '-0.25rem 0rem 0rem', fontSize: '1.25rem', fontWeight: '400' }}>
                      Feels Like {Math.round(observations.data.wl.feelsLike)}°
                    </p>
                  ) : (
                    <></>
                  )}
                  <div style={{ display: 'flex', alignItems: 'center', margin: '1rem 0rem 1rem' }}>
                    <img
                      src="pcloudy.png"
                      style={{ width: '2rem', objectFit: 'scale-down', marginRight: '0.5rem' }}
                    ></img>
                    <p style={{ margin: '0.25rem 0rem 0rem', fontSize: '2rem', fontWeight: '400' }}>
                      {observations.data.nws?.textDescription}
                    </p>
                  </div>
                </div>
                <div
                  style={{ display: 'flex', flexWrap: 'wrap', flex: '1 1', maxWidth: '36rem', justifyContent: 'end' }}
                >
                  <CardDetail
                    value={`${Math.round(observations.data.wl?.wind.speed ?? 0)} mph ${getWindDirection(
                      observations.data.wl?.wind.direction ?? 0
                    )}`}
                    secondaryValue={`${Math.round(observations.data.wl?.wind.gustSpeed ?? 0)} mph gusts`}
                    iconImgSrc="arrow.png"
                    label="Wind"
                  />
                  <CardDetail value={`X`} secondaryValue={`XXX`} label="UV Index" />
                  {observations.data.airnow?.observations?.length ? (
                    <CardDetail
                      value={String(observations.data.airnow.observations[0].aqi ?? '–')}
                      secondaryValue={observations.data.airnow.observations[0].aqiLevelName ?? '–'}
                      label={`Air Quality (${observations.data.airnow.observations[0].pollutant})`}
                    />
                  ) : (
                    <CardDetail value={`–`} secondaryValue={`–`} label="Air Quality" />
                  )}

                  <CardDetail value={`${Math.round(observations.data.wl?.humidity ?? 0)}%`} label="Humidity" />
                  <CardDetail
                    value={`${observations.data.wl?.pressure.atSeaLevel?.toFixed(2) ?? '–'} in ${
                      observations.data.wl?.pressure.trend ? (observations.data.wl.pressure.trend > 0 ? '↑' : '↓') : '→'
                    }`}
                    label="Pressure"
                  />
                  <CardDetail
                    value={`${observations.data.wl?.rainfall.last24Hrs?.toFixed(2) ?? '–'} in`}
                    label="Last 24hr Rainfall"
                  />
                </div>
              </div>
            </div>
          </>
        ) : (
          <>
            <h1>Something went wrong :(</h1>
            <br />
            {observations?.errors.map(error => (
              <h3 key={error}>{error}</h3>
            ))}
          </>
        )
      ) : (
        <h1>Loading...</h1>
      )}
    </div>
  );
}
